### ISSUE TITLE
vm-disk-type не меняет тип диска при создании ВМ

### ISSUE THREAD

**Issue by avixFF** [yc-actions/yc-coi-deploy#254]
Добрый день! Я создал PR #253, который добавляет параметр `vm-disk-type`. Однако используя версию action из своего форка и мерджнутый PR в данный репозиторий у меня все равно создается ВМ с типом диска SSD:

![image](https://user-images.githubusercontent.com/3730149/201528295-e4e004a5-ff90-4eb9-bbe3-a0d83ea8e5eb.png)

Может быть как-то можно вывести логи из SDK YC чтобы посмотреть причину, по которой он не создает ВМ с `network-hdd`?

**Comment by nikolaymatrosov** [comment]
Приложите отладочную информацию. Ссылку на репозиторий например.

**Comment by avixFF** [comment]
Репозиторий приватный, однако вот логи при запуске экшена:

```
2022-11-13T15:05:49.4277393Z ##[group]Run yc-actions/yc-coi-deploy@main
2022-11-13T15:05:49.4277988Z with:
2022-11-13T15:05:49.4284809Z   yc-sa-json-credentials: ***
2022-11-13T15:05:49.4285431Z   folder-id: ***
2022-11-13T15:05:49.4285843Z   vm-name: ***-preview
2022-11-13T15:05:49.4286306Z   vm-service-account-id: ***
2022-11-13T15:05:49.4286740Z   vm-zone-id: ru-central1-a
2022-11-13T15:05:49.4287158Z   vm-subnet-id: ***
2022-11-13T15:05:49.4287591Z   vm-platform-id: standard-v3
2022-11-13T15:05:49.4287960Z   vm-cores: 2
2022-11-13T15:05:49.4288315Z   vm-core-fraction: 20
2022-11-13T15:05:49.4288695Z   vm-memory: 1GB
2022-11-13T15:05:49.4289064Z   vm-disk-type: network-hdd
2022-11-13T15:05:49.4289500Z   user-data-path: yandex-cloud/user-data.yml
2022-11-13T15:05:49.4290032Z   docker-compose-path: yandex-cloud/docker-compose.yml
2022-11-13T15:05:49.4290473Z   vm-disk-size: 30GB
2022-11-13T15:05:49.4290822Z env:
2022-11-13T15:05:49.4310722Z   IMAGE_URL: cr.yandex/***/***:dev-b2926b3862d25319b245e79b05d55955c0c90503
2022-11-13T15:05:49.4317899Z ##[endgroup]
2022-11-13T15:05:49.5878105Z start
2022-11-13T15:05:49.5886555Z ##[group]Parsing Action Inputs
2022-11-13T15:05:49.5891142Z ##[endgroup]
2022-11-13T15:05:49.5893723Z Folder ID: ***, name: ***-preview
2022-11-13T15:05:49.5896065Z Parsed Service account JSON
2022-11-13T15:05:49.6005558Z ##[group]Find VM by name
2022-11-13T15:05:50.7378173Z ##[endgroup]
2022-11-13T15:05:50.7381645Z ##[group]Find COI image id
2022-11-13T15:05:50.9503847Z COI image id: fd80o2eikcn22b229tsa
2022-11-13T15:05:50.9504841Z ##[endgroup]
2022-11-13T15:05:50.9505564Z ##[group]Create new VM
2022-11-13T15:06:23.6970151Z ##[endgroup]
```

**Comment by nikolaymatrosov** [comment]
Попробуйте добавить логгирования в ваш форк и найти почему не работает.

**Comment by avixFF** [comment]
Попробовал добавить вывод с помощью `core.debug`, однако при сборке с помощью `npm run all` получаю следующую ошибку при выполнении:

```
Error: Cannot find module 'node:http'
Require stack:
- /home/runner/work/_actions/avixFF/yc-coi-deploy/feature/vm-disk-type/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Module.401 (/home/runner/work/_actions/avixFF/yc-coi-deploy/feature/vm-disk-type/webpack:/yc-actions-yc-coi-deploy/external node-commonjs "node:http":1:1)
    at __nccwpck_require__ (/home/runner/work/_actions/avixFF/yc-coi-deploy/feature/vm-disk-type/webpack:/yc-actions-yc-coi-deploy/webpack/bootstrap:21:1)
    at Object.1284 (/home/runner/work/_actions/avixFF/yc-coi-deploy/feature/vm-disk-type/webpack:/yc-actions-yc-coi-deploy/node_modules/@nikolay.matrosov/yc-ts-sdk/lib/src/TokenService/metadataTokenService.js:7:1)
    at __nccwpck_require__ (/home/runner/work/_actions/avixFF/yc-coi-deploy/feature/vm-disk-type/webpack:/yc-actions-yc-coi-deploy/webpack/bootstrap:21:1)
    at Object.4928 (/home/runner/work/_actions/avixFF/yc-coi-deploy/feature/vm-disk-type/webpack:/yc-actions-yc-coi-deploy/node_modules/@nikolay.matrosov/yc-ts-sdk/lib/src/index.js:5:1)
    at __nccwpck_require__ (/home/runner/work/_actions/avixFF/yc-coi-deploy/feature/vm-disk-type/webpack:/yc-actions-yc-coi-deploy/webpack/bootstrap:21:1)
```

Собирал в GitHub Codespaces

Вот коммит со сборкой: https://github.com/avixFF/yc-coi-deploy/commit/2d8bf7f29fb9084a09e4bbbc1e2c4b15f8fd4876

Как правильно собрать данный экшн?

**Comment by nikolaymatrosov** [comment]
Попробуйте еще раз с новой версией экшена.

**Comment by avixFF** [comment]
Похоже проблема была банально в том, что я не пересобрал экшн, потому что сейчас создается диск HDD.
Я думал экшн сам через пайплайн при медже пересобиратся

В любом случае создал PR #257, который добавляет логирование (нужно установить секрет `ACTIONS_STEP_DEBUG` в `true`).

Используя объект `Instance`, который теперь логируется, я хочу добавить выводы для данного экшена (id машины, id диска и публичный IP). Как сделаю открою ещё один PR.
